spring:
  application:
    name: websocket
server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: eu-west-2
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
